### ISSUE TITLE
SSH - ciphers and keyalgorithms

### ISSUE THREAD

**Issue by kamilboratynski** [CISOfy/lynis#102]
I would like to post it here to avoid forgetting it. [[1](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_server)]

It would be nice to implement checking ciphersuites and keylgorithms (as it might be done for webservers too). I think this one should be out of function `[SSH-7408]`, for simple reason. If somone has more stricted ciphers, we cannot say, they're wrong. ;-)

[[1](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_server)]: https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_server

**Comment by rhyven** [comment]
I'd really like to see this.  It's important to be careful, because people can break their SSH by using kex / ciphers / MACs that are too modern, but on my systems, I use the following:

```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
# Prefer Curve25519; allow DH-group-sha256 for compatibility
# Curve25519 avoids NIST curves, and is immune to several side-channel attacks: http://ed25519.cr.yp.to/

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr
# Prefer Chacha20; allow strong AES for compatibility
# http://googleonlinesecurity.blogspot.co.nz/2014/04/speeding-up-and-strengthening-https.html

MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
# SHA2 only; prefer Encrypt-Then-MAC options, and prefer 512b options
```

**Comment by kboratynski** [comment]
@rhyven 
The same with SSL protocol on webservers. It would be nice to have checking `Diffie-Hellman` parameters (if they are present in `dh_params` for `nginx` or attached at the end of certificate file).

I am working on it.
In fact, it will be `O(n)=n^2` algorithm because I have to loop over expected ciphers and found ciphers, but for such a `n`... ;-)

**Comment by mboelen** [comment]
For now, I suggest to check for strong ciphers and reward that, while still allowing some "weaker" ones for compabitiliy (at the end). This way systems don't get broken, and people have the option to harden it to the extent they want. Seems like a good option to add.

**Comment by lpirl** [comment]
Yes, this would be a relevant enhancement. 
[This article, also recommends algorithms](https://stribika.github.io/2015/01/04/secure-secure-shell.html) to prefer and includes some explanations.

**Comment by mboelen** [comment]
Feel freel to add pull requests if you see improvements. Please specify them with the pull request, so we can add details to the website, like explaining why one would choose a specific cipher or protocol, and how to configure it.

**Comment by mboelen** [comment]
Closing issue for now, as no actions were taken. The subject is still on our radar though.

**Comment by quantumpacket** [comment]
It is not beneficial to close issues prematurely before they have been fully resolved. Keeping issues open allows for continued engagement from contributors, and allows for progress to be made in addressing the issue. Closing an issue simply because no action has yet been taken does not improve the overall quality of Lynis. It is important to remember that contributors volunteer their time and efforts, and there should not be a fixed timeline for when a pull request should be submitted before an issue is closed.

By prematurely closing issues, it makes it harder for current and future contributors to identify and address open issues. When an issue is closed, it is often assumed that it has been properly resolved, and therefore, it is less likely to be revisited. This can result in important issues being overlooked, as demonstrated by my experience searching for a specific issue related to `KexAlgorithms`.

I urge you to reevaluate your current closing policy, as it is hindering progress and visibility of open issues. It is important that issues are kept open and visible in order to ensure they are properly addressed.
