### ISSUE TITLE
[SSH] -- port forwarding

### ISSUE THREAD

**Issue by kboratynski** [CISOfy/lynis#106]
Writing the tests to `SSH`, I decided to do not include forwarding options as a security hole and let us discuss it.

We are discussing options:
`GatewayPorts`,
`PermitTunnel`
`AllowTcpForwarding`

In my opinion, tunneling might be an security hole, because it allows omitting firewall.

**Comment by rhyven** [comment]
I think port forwarding is OK, provided it's done selectively... we use it heavily here to provide access to the terminal server via a secure SSH tunnel for remote users.

(see note in man page: *Note that disabling TCP forwarding does not improve security unless users are also denied shell access, as they can always install their own forwarders.*)

`GatewayPorts` seems to be particularly open - this is probably a "NO" for me.
`PermitTunnel` could be OK if it's inside a MATCH directive... programming for this would be tricky though, so I think "NO".
`AllowTcpForwarding` -- this is the one I'm wondering about most, simply because we rely on it so heavily here.  How about the following:
* "YES" is very bad;
* "LOCAL" is ok 
* "NO" is good.

More thoughts?

**Comment by kboratynski** [comment]
<blockquote>
(see note in man page: Note that disabling TCP forwarding does not improve security unless users are also denied shell access, as they can always install their own forwarders.)
</blockquote>
I am aware of this, but this is the idea of hardering services, I think. Closing as much as possible. :-)

For me:
- `GatewayPorts` -- definitely, `NO`; no ifs.
- `PermitTunnel` -- I am thinking of parsing `Match` directive; be patient :-); for now: `NO`,
- `AllowTcpForwarding` -- I have the same idea for grading as you.

**Comment by rhyven** [comment]
I like  :)  :+1:

**Comment by kboratynski** [comment]
Merged.
