### ISSUE TITLE
sshd config DisableForwarding

### ISSUE THREAD

**Issue by suruaku** [CISOfy/lynis#1126]
**Describe the bug**
I have `DisableForwarding yes` which means "Disables all forwarding features, including X11, ssh-agent(1), TCP and StreamLocal." [source](https://manpages.debian.org/unstable/openssh-server/sshd_config.5.en.html#DisableForwarding)

When I run `lynis audit system` I get suggestions to disable X11, TCP, Agent.

**Version**
 - Distribution Ubuntu 20.04
 - Lynis version 3.0.3

**Expected behavior**
Not suggest disabling what is already disabled.

**Output**

```
* Consider hardening SSH configuration [SSH-7408]
    - Details  : AllowTcpForwarding (set YES to NO)
      https://cisofy.com/lynis/controls/SSH-7408/

  * Consider hardening SSH configuration [SSH-7408]
    - Details  : X11Forwarding (set YES to NO)
      https://cisofy.com/lynis/controls/SSH-7408/

  * Consider hardening SSH configuration [SSH-7408]
    - Details  : AllowAgentForwarding (set YES to NO)
      https://cisofy.com/lynis/controls/SSH-7408/
```

**Comment by lberrymage** [comment]
Still relevant

**Comment by mboelen** [comment]
Thanks for reporting this. Yes, you are correct that if you enable that setting that it turns off the other protocols. It is a shame that the SSH daemon itself does report back correctly. Would have been nice if they track the relationships (if option X is set, then option A, B, and C, are also set) and report that in the active output.

Although we could make changes to the Lynis code and detect this (read: put the intelligence on the side of Lynis instead of the sshd output), I'm opting at this moment not to make changes. The primary reason is that the SSH daemon configuration options are changing between releases, including the defaults. Although `DisableForwarding` might at this moment change these other settings, it may have a different value in a future release. As you can imagine, it can become a serious burden to track these specific combinations and related settings with all combinations of versions.

My suggestion is to explicitly disable these other settings (TCP/X11/Agent) in your SSH daemon configuration or disable these specifics tests in the Lynis configuration (custom.prf).

Will close this ticket for now without any changes to the code, as explained above.
