### ISSUE TITLE
lynis for AMI (Amazon Machine Image)

### ISSUE THREAD

**Issue by amankumarchagti** [CISOfy/lynis#1210]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. How would it help you to make things easier? Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Using lynis in amazon Linux for security assessments
**Required changes**
Adding support for Amazon Linux
**Additional context**
Add anything else that you consider to be relevant about the feature request here.

**Comment by mboelen** [comment]
Lynis should already run on Amazon Linux. What specifically is not working?

**Comment by amankumarchagti** [comment]
how to use it?? like installation and scan, etc.

**Comment by konstruktoid** [comment]
Is there any issues following the instructions at https://github.com/CISOfy/lynis#git?

**Comment by mboelen** [comment]
@amankumarchagti please follow the details listed in the documentation, like the [get started](https://cisofy.com/documentation/lynis/get-started/) section. Most likely you can install Lynis from a package. Otherwise, try the tarball or git method.

If there is not a specific issue with Amazon Linux, then let's close this issue.

**Comment by amankumarchagti** [comment]
sure, the issue is solved. Thank you
