### ISSUE TITLE
Tests_time  167: /usr/local/lynis/include/tests_time: /usr/bin/grep -E: not found

### ISSUE THREAD

**Issue by JMarianoIFSTTAR** [CISOfy/lynis#1430]
**Describe the bug**
Errors on tests_time after Lynis update

**Version**
 - Distribution Ubuntu 22.04
 - Lynis version 3.0.9

**Expected behavior**
No error message 

**Output**
Multiple (24) lines like : 
/usr/local/lynis/lynis: 167: /usr/local/lynis/include/tests_time: /usr/bin/grep -E: not found

**Context / Hint **
- Don't have ntpdate, rdate, sntp or ntpdig  (cf ${CRONTAB_REGEX}) 
- There is a warning just below for "Checking for a running NTP daemon or client"

**Comment by mboelen** [comment]
Thanks for reporting. Confirmed and with commit https://github.com/CISOfy/lynis/commit/9d9cedee4ef4b1ab79d7288cb9bb3242d92b4939 it should be solved.

Closing issue, but feel free to let me know if it fails.

Regarding the time thing: please put it in a fresh issue with all details (e.g. output), so that we can have a look at it.
