### ISSUE TITLE
facilitate auditing of untrusted hosts

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis#229]
When generating a hardening report on a not fully trusted host – say it is exposed to the internet with a lot of not fully trusted services – the report itself can be questioned due to the use of untrusted binaries.

An option like [`chkrootkit`'s possibility to specify the root directory to test and/or the path to the binaries to use](http://www.chkrootkit.org/faq/#5) would be very handy.

I am aware that this issue is not easy to resolve but we could keep it and gradually implement this.

**Comment by mboelen** [comment]
That kind of functionality I actually created for rkhunter in the day. Not that hard to add a new binary path to scan. We will give it some thought to see what could work here. Thanks for the idea :+1:

**Comment by mboelen** [comment]
Hi @lpirl, the --bin-dirs options has been added. Can you help testing?

**Comment by lpirl** [comment]
Thanks @mboelen !
How does `--bin-dirs` actually work? I see it is considered in [include/binaries](https://github.com/CISOfy/lynis/blob/32fd85155d696fd80011397f42725a58914712da/include/binaries) but the `…BINARY` variables do not seem to be used consistently.
If the solution does not provide significantly more trust, I might consider to

1. sshfs-mount the remote `/` on a trusted machine
2. mount a trusted `/bin`, Lynis installation, etc. into the chroot
3. run Lynis inside the chroot with `PATH` overridden

**Comment by mboelen** [comment]
It sets the binary paths to scan (similar like you would change your PATH). As you can imagine, this change has to be applied in phases, so that every single binary used is defined. For that it would be good to do testing together. One thing I was thinking of is adding some "canary" binaries in the normal directories, which get triggered when used. This way we instantly know when a test still uses a binary from the normal paths (instead of your custom defined one).

This change goes together with the --root-dir addition. So if you have the chance, start using this new option and see how it does work on your systems. We will do some testing later on ourselves, comparing command outputs etc.

**Comment by lpirl** [comment]
@mboelen, thanks for your reply. I understand what you wrote.
Nevertheless, let me try to rephrase my concerns more precisely: even if `--bin-dirs` is used, most of the tests just seem to call the binaries directly (e.g. `egrep` and `awk` [here](https://github.com/CISOfy/lynis/blob/cde3f85b574b56d7ae4de9c373a03dddba316e4f/include/tests_ssh#L244)) instead of using the `…BINARY` variables provided by [include/binaries](https://github.com/CISOfy/lynis/blob/32fd85155d696fd80011397f42725a58914712da/include/binaries).
As a result, using `--bin-dirs` seems to affect very few binaries used by the tests.

1. Is there some magic somewhere that I overlooked that replaces the (ordinarily called) binary (say `egrep`) from `PATH` with the one from `--bin-dirs`?
2. Wouldn't it be easier to overwrite `PATH` completely? That way, all binaries (w/o an absolute path) would be affected.
3. What "`--root-dir`addition"? :) (This would be much easier to test: run on trusted host with remote file system root mounted, instead of: providing read-only binaries on an untrusted host).

**Comment by mboelen** [comment]
Yes, some references are still to the binary name, instead of a variable. In small batches we replace them. Most egrep, grep, and awk references are now changed in the tests: https://github.com/CISOfy/lynis/commit/679e8c628e2a42df13bec79da256b1bf7b68d6b3 Next in line are ls, ps, sort, etc.

1. No, you didn't overlook it. We don't use PATH at all.
2. Lynis has the goal to do its detection on its own, so it ignores PATH
3. See include/parameters for all options. We added `--root-dir` recently, which is like `--bin-dirs` a work in progress. It allows you to scan a mount point (e.g. for Linux forensics). You can then use the --bin-dirs to instruct Lynis to use the binaries from the mount point, your local system, or somewhere else.

Does that make sense? Thanks for the questions :)

**Comment by lpirl** [comment]
Alright I see. Thanks @mboelen.

Very sad that we do not have a way of reliably redirecting all calls to binaries.
However, this is "better than nothing" and will improve over time.

Well, maybe clearing `PATH` and observing what fails might be an option?

I do want to check out this feature (i.e. help testing by opening PRs/issues if something goes wrong) but I cannot commit to do so at the time.

Feel free to close the issue if you like, leaving it open as "work in progress" is fine as well.

**Comment by mboelen** [comment]
Closing this issue for now, as part of a bigger clean up. More changes will be made in upcoming releases to better support this feature request.
