### ISSUE TITLE
wrong report for fail2ban under centos

### ISSUE THREAD

**Issue by atao60** [CISOfy/lynis#233]
ATM Lynis makes two wrong assumptions under CentOS:
- the prefix for fail2ban chain in iptables is not fail2ban but f2b (see issue #206)
- jail.local overwrites jail.conf as a whole but fail2ban merges the two files

Furthermore "Checking Fail2ban jails" status is not displayed as some i18n status values are not translated in all languages.

[lynis_f2b.patch.zip](https://github.com/CISOfy/lynis/files/368176/lynis_f2b.patch.zip)

**Comment by mboelen** [comment]
Is this patch provided tested against CentOS only?

**Comment by atao60** [comment]
yes

I'll have the opportunity to install Lynis under Debian but not until next week. I'll then test the patch.

**Comment by atao60** [comment]
About the i18n part: is it on purpose the project doesn't use the sh shell buildin gettext features?

**Comment by mboelen** [comment]
The test has been rewritten to use the client instead of configuration files. This way we pick up on the actual processed data. Have a look at recent commits and see if that improved it for you as well.

Regarding i18n: current method looked easier and there were doubts regarding support for all shells (csh/sh/ksh), especially on other platforms than Linux. So just keeping things simple.
