### ISSUE TITLE
Kernel Hardening Output vs default.prf entries?

### ISSUE THREAD

**Issue by Geyup** [CISOfy/lynis#262]
I'm using  lynis-2.3.2 in Slackware 14.2 x86_64.

In /etc/lynis I only have one file, ```custom.prf``` edited from default.prf. I didn't make any changes to the;

Processes
Kernel
Network

When I run as, ```lynis audit system``` this is the output for the Kernel Hardening;

Kernel Hardening
  - Comparing sysctl key pairs with scan profile             
    - kernel.core_uses_pid (exp: 1)                           [ OK ]
    - kernel.ctrl-alt-del (exp: 0)                            [ OK ]
    - kernel.kptr_restrict (exp: 2)                           [ OK ]
    - net.ipv4.conf.all.accept_redirects (exp: 0)             [ OK ]
    - net.ipv4.conf.all.accept_source_route (exp: 0)          [ OK ]
    - net.ipv4.conf.all.bootp_relay (exp: 0)                  [ OK ]
    - net.ipv4.conf.all.forwarding (exp: 0)                   [ OK ]
    - net.ipv4.conf.all.log_martians (exp: 1)                 [ OK ]
    - net.ipv4.conf.all.mc_forwarding (exp: 0)                [ OK ]
    - net.ipv4.conf.all.proxy_arp (exp: 0)                    [ OK ]
    - net.ipv4.conf.all.rp_filter (exp: 1)                    [ OK ]
    - net.ipv4.conf.all.send_redirects (exp: 0)               [ OK ]
    - net.ipv4.conf.default.accept_redirects (exp: 0)         [ OK ]
    - net.ipv4.conf.default.accept_source_route (exp: 0)      [ OK ]
    - net.ipv4.conf.default.log_martians (exp: 1)             [ OK ]
    - net.ipv4.icmp_echo_ignore_broadcasts (exp: 1)           [ OK ]
    - net.ipv4.icmp_ignore_bogus_error_responses (exp: 1)     [ OK ]
    - net.ipv4.tcp_syncookies (exp: 1)                        [ OK ]
    - net.ipv4.tcp_timestamps (exp: 0)                        [ OK ]

When I look at the custom.prf to see all the entries for the;

Processes
Kernel
Network

I don't understand why I am not seeing all these entires at the terminal when I run ```lynis audit system``` under the ```Kernel Hardening``` output?

The output I pasted above only shows 19 entires, the default.prf shows 42 entries listed by default, why are not all 42 entires being display in the ouput when running ```lynis audit system```?

**Comment by mboelen** [comment]
Great question. Non-existing keys are not displayed (as they can't be configured anyways). It does also include keys for FreeBSD for example.

**Comment by mboelen** [comment]
As your question involved another issue, we have made some changes today to the code.

Have a look at the new format for dealing with sysctl settings (in default.prf). If you add it to your custom.prf, they should also show up now. Non-existent keys will never show though, as explained.

Did this solve your issue?

**Comment by Geyup** [comment]
```Non-existent keys```, I don't understand, I thought all of the Kernel sysctl configuration options one could consider exist for every distro the same?

**Comment by mboelen** [comment]
Every Linux distribution, or UNIX-based operating system, has different keys. Sure, there is some overlap, but it depends on your kernel version, what the distribution implemented, etc.

Yes, your system has a lot of them. Lynis is not interested in all of them, because some are specific to your network interfaces (so you get more sysctl keys if you have more interfaces). Lynis checks for those keys that have a special value for security purposes.

Does that help?

**Comment by Geyup** [comment]
Yes of course security is what we're talking, just wasn't sure if any of these I have are also related to the topic...

Also what about RFC 5961 issue, dating back to kernel 3.6x...

Is this a concern Lynis should be looking at, and I read it's suppose to be fixed in 4.4.18, but not sure...

And I read this is somewhat a way around, till the fix comes out;

```net.ipv4.tcp_challenge_ack_limit = 999999999```

**Comment by mboelen** [comment]
For temporary keys you like to test, or any others, you can add them to your custom.prf. This way you can customize the things you want to check. In this case the TCP challenge ACK limit is a network related setting. While we are aware of the issue surrounding it (and the workaround you have listed here), this is something we don't check at this moment. Otherwise, we would have to check the specific kernel, any patches, and compare the sysctl value. Instead, just add it to your custom.prf and remove when you have the fix in place.

If you have security related keys that you think should be in Lynis, feel free to create pull requests. We definitely appreciate any thoughts when it comes to further improve security defenses. Thanks!

**Comment by Geyup** [comment]
I'm not following here with the ```temporary keys```?

I'm assuming at this link are my keys?

http://dpaste.com/3QNFAV6

If so, then how would I know, because I'm looking at the defaults in a distro, now I'd have to go online and research to determine if these are hardened or not, so really this seems pointless as an end-user, because now I'm making the judgement call here, as to what changes to make, rather then what Lynis is telling me when I use it...

Make sense if I'm on the right track?

Pull requests I'm not geek enough for all this, I need the experts here to do all this...

thanks
