### ISSUE TITLE
Naming Convention for macOS

### ISSUE THREAD

**Issue by jpartain89** [CISOfy/lynis#309]
While looking through all of the code, it looks like the formatting of `macOS` is a tad bit all over the place. While it might not necessarily cause issues, with macOS being case-sensitive, and having a stray `Macos` or `MacOS` could potentially cause issues. 

I'm submitting this here rather than a pull request, because there is simply SO MANY instances of `macOS`

**Comment by mboelen** [comment]
Good observation. The detection string to see if a test needs to be executed is "MacOS". This is since the time that it was Mac OS X. It would be fine to replace all strings that refer to Mac OS X and "MacOS" and replace them with the new "macOS".

Although an inline grep and replace could be done, this might be better be done in phases (e.g. per file), to ensure that things don't break. Obviously filtering on "mac" might trigger replacement of the unrelated terms like "MAC" and "machine".

**Comment by jpartain89** [comment]
So, just to confirm on this one, for the OS's that are 10.11 and below (El Capitan and lower) the OS= should be "macOS" for ubuquity and simplicity sake. But do we want to keep the "Mac OS X El Capitan" nomenclature for earlier versions, aka OS_FULLNAME?

**Comment by marcus-cr** [comment]
Gotta love Apple's rebranding... I second this proposal. 

For simplicity it would seem best to stick with `OS=macOS` and `OS_FULLNAME=Mac OS X El Capitan`. Apple seems to be remaining faithful to their pre-10.12 version names.

**Comment by mboelen** [comment]
As this has been implemented by @jpartain89 in https://github.com/CISOfy/lynis/commit/50b06efd303fa82284dfa1fd083ed18fa8a55ec6, I'm closing this issue. Thanks :)

OS=macOS
OS_FULLNAME depends on the version (before 10.12 will be Mac OS X, otherwise macOS).
