### ISSUE TITLE
hangs in /usr/bin/journalctl --list-boots 

### ISSUE THREAD

**Issue by jots** [CISOfy/lynis#314]
on CentOS Linux release 7.2.1511 (Core)

when running it hangs at: 
 - Plugin: systemd
    [.......]

top show this using 100% cpu:
 /usr/bin/journalctl --list-boots

may be related to https://github.com/systemd/systemd/pull/3114  which I haven't dug into yet.

**Comment by mboelen** [comment]
Looks like you found the right cause. As this issue is in an external tool, we can't fix it. Normally we would look into working around the issue by doing a specific check. In this case, there is not an obvious check to perform.

So one thing you could do is exclude the particular test in your custom.prf profile. Do you have it on all your systems, or just one?

**Comment by mboelen** [comment]
Hi @jots, can you answer the question above? Then we can make a decision regarding this issue.

**Comment by mboelen** [comment]
Closing issue, as no response came and we did not hear any other complaints.
