### ISSUE TITLE
Check modify time of old files instead of access time

### ISSUE THREAD

**Issue by aw** [CISOfy/lynis#324]
Hi,

Just looking at [include/tests_filesystems](https://github.com/CISOfy/lynis/blob/master/include/tests_filesystems#L337) I noticed the `-atime` flag is used for files in `/tmp` which may not provide useful results:

1. Occasionally filesystems are mounted with `noatime`, so that value would never be updated.
2. It is possible for a file to be modified without the `access time` being modified, therefore you _could potentially_ have a recent file which is considered old.
3. Busybox's `find` doesn't include the `-atime` flag - which causes this test to succeed silently.

> Perhaps I can suggest changing it to `-mtime`

Thanks!

**Comment by mboelen** [comment]
Thanks for the digging work :) We actually had it at mtime before, but due to the nature of storing temporary files, it is more interesting to know what files are recently used. All others are good candidates for being cleaned, obviously with checking first by the admin.

The test will never be perfect, as there are a lot of different use-cases and many software packages dealing with /tmp in a different way. So we consider this test to be a nice-to-have to catch some old files. But if it is not effective for your system, then disabling it in a custom.prf makes sense.

Let me know if you have any other thoughts. Will close this issue for now.
