### ISSUE TITLE
PHP support for cPanel installations

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#340]
/opt/cpanel/ea-phpXX/root/etc/php.ini
/opt/cpanel/ea-phpXXroot/etc/php.d (directory)

XX can be a version number.

**Comment by athmane** [comment]
Hi @mboelen ,

Those paths are related to the fact that cPanel switched to Scl based packages for php and other LAMP stuff (EasyApache 4), I've added hardcoded paths in PR #373, you may find the relevant part of a test in [1] (cant share full logs since it's a $dayjob box). 

IMHO the preferred solution is to list the installed Scl using ```scl -l```  and/or ``` rpm content listing```, then generate the correct paths, however I'm guessing that Lynis avoided that in the first place for existing paths because of potential security issues (running external command !), let me know if it's the case or not to update the code. 

```
] $ scl -l
ea-php56

```

[1] https://gist.github.com/athmane/e8754233a1acf921d2c58da975f37130

**Comment by mboelen** [comment]
Hard-coded paths are good for now. Later we will rewrite parts of this PHP test to do a more smart checking for the locations.
