### ISSUE TITLE
Sick of Bad Coding

### ISSUE THREAD

**Issue by say2joe** [CISOfy/lynis#358]
I can't believe I'm seeing this on a brand-new install of Kubuntu with Lynis recently installed. WTF?!?!

What if I was already hacked... how does this shitty WTF message help????

Any competent programmer should be able to write something a little better for new users. My Internet (wifi) connection is working fine, along with Chrom(ium)e [writing this msg now]. I just can't stand how someone might need to use this software quickly to detect an intrusion and yet they have to deal with this crap ...

      ===============================================================================
        Lynis update available
      ===============================================================================

        Current version is more than 4 months old

        Current version : 232   Latest version : 243

        Please update to the latest version.
        New releases include additional features, bug fixes, tests and baselines.

        Download the latest version:
        Packages (DEB/RPM) -  https://packages.cisofy.com
        Website            -  https://cisofy.com/downloads/
        GitHub             -  https://github.com/CISOfy/lynis

      ===============================================================================

Error: Unknown protocol, please specify (http, https) in profile (update_server_protocol)

**Comment by say2joe** [comment]
Nothing in a quick google search produced valuable results. This is bullshit for security-based software.

**Comment by mboelen** [comment]
**Self-reflection**

> Is this how you start conversations with people? You are free to use Lynis and we continuously update it to make it better. Calling it crap and bullshit is disrespectful. Sharing feedback is fine. But if you can't say nice things, maybe you should reconsider your wording next time.

**Solution**

For all others that may find this thread, here are possibility steps to solve this:
- Ensure that Lynis is installed only once on the system. Otherwise, an old configuration might be picked up and you will receive this error. A previous installation could be available in your home directory or in /usr/local/lynis
- Remove the old default.prf from /etc/lynis (if present)
- Install the latest package from https://packages.cisofy.com
- Run Lynis again
