### ISSUE TITLE
Suggestion: add Ansible in tests_tooling

### ISSUE THREAD

**Issue by dminca** [CISOfy/lynis#436]
Hi there,

We're running Ansible in our Infrastructure and we saw there are checks in `./include/tests_tooling` regarding Puppet, Chef et. al. but we couldn't find anything on Ansible.

Could a check for Ansible be added as well? Would be really useful to see whether Ansible is installed on a system or not.

**Comment by mboelen** [comment]
The 'problem' with Ansible is that there is no client running on the system. So if you have a suggestion and easy way to detect it, we love to hear.

**Comment by quantumpacket** [comment]
Correct me if I am wrong, but I think @dminca may be referring to detecting if Ansible is installed on a bastion host used for administrating Ansible clients, which is the recommended "secure" way to use Ansible. In that case checking is straightforward.

**Comment by dminca** [comment]
That's exactly what I was referring to, given Ansible's agentless execution.

@mboelen one example check might be: `ansible --version` if it's a success then Ansible is installed on that host. What do you guys think?

**Comment by quantumpacket** [comment]
According to the [docs](https://docs.ansible.com/ansible/latest/intro_installation.html#running-from-source) a *lot of people* use the source version. So they may not necessarily have Ansible installed as a package and in a known location.

They provide an environment setup script, which will add the installation bin directory to `$PATH` for the current session with the following:

```sh
PREFIX_PATH="$ANSIBLE_HOME/bin:$ANSIBLE_HOME/test/runner"
expr "$PATH" : "${PREFIX_PATH}.*" > /dev/null || export PATH="$PREFIX_PATH:$PATH"
```

Since the setup script does not permanently add the path, Lynis will not be aware of the Ansible install directory to be able to run `ansible --version`. If we want to not support detection of source installs then that would suffice, but otherwise we may need a Lynis config entry where we can specify a location(s) to check for the Ansible executable.

Just a potential issue, but personally I'd rather not complicate things. Besides we have no real gauge of how many people actually use the source version.

**Comment by dminca** [comment]
@quantumpacket who on earth would use it installed as source when you can `apt-get install ansible` or `pip install ansible`, why would you complicate it so much?

Honestly, I think it's easier to just check the return code of ansible version, that's the plain and simple check. If you guys want something more complex there are also other ways...

**Comment by lpirl** [comment]
for reference: #212

**Comment by quantumpacket** [comment]
Thanks @lpirl, https://github.com/CISOfy/lynis/issues/212#issuecomment-299674969 seems like a good method, but as far as I can tell that directory will only be present upon Ansible being run at least once. So using both `ansible --version` and checking for `~/.ansible` should cover all but one case (Ansible installed as source, but hasn't been run yet). I think that's a good compromise.

**Comment by Antauri** [comment]
As far as I can see, running Ansible commands on a node, leaves a ton of information in /var/log/syslog. That's a good enough check from my POV that the NUP (node under provisioning) is being tooled by Ansible, even when Ansible is not installed on that node . You could look in the default places where Ansible leaves a mark of it being there and tests those.

**Comment by BusinessConnect** [comment]
Using syslog isn't perfect IMO since ansible can be used once a week. It is managed but the logfile can be logrotated. Also, syslog can be inactive or logging can be directed to other destinations.

Besides that; searching logfiles is not a very fast solution.

I would go for the option suggested by @quantumpacket

**Comment by quantumpacket** [comment]
My draft proposal would be the following then:

 - check for the existence of an installed Ansible package using `ansible --version`
 - check for the existence of an Ansible package or source version by looking for `~/.ansible`
   - we should check all `/home/USER` directories since Ansible may not be run as the same user as Lynis. Can system accounts be used for Ansible, where no home directory is made? :worried: 
 - also check for `/root/.ansible` and warn/penalize if found, since you really should not be running it as the root user, but use the `become` directive instead. Can only be checked if Lynis is run as root for a full audit.

Does anyone see any possible issues with this?

**Comment by dminca** [comment]
Those are all good suggestions @quantumpacket . I would also propose to check the following:
- check for the existence of `/etc/ansible` (this is where it [holds configuration file][1])
- check for the existence of `/var/log/ansible.log` (see [ansible.cfg][2])
- check for the existence of Ansible retry files (these files output server names that failed to execute in the playbook) in `~/.ansible-retry` (see [ansible.cfg][3])
- check for Ansible control path `/tmp/.ansible` (see [ansible.cfg][4])

[1]: https://github.com/ansible/ansible/blob/5ee7862793abc94c519e5b6d8e7d096563f092b4/examples/ansible.cfg#L14
[2]: https://github.com/ansible/ansible/blob/5ee7862793abc94c519e5b6d8e7d096563f092b4/examples/ansible.cfg#L104
[3]: https://github.com/ansible/ansible/blob/5ee7862793abc94c519e5b6d8e7d096563f092b4/examples/ansible.cfg#L239
[4]: https://github.com/ansible/ansible/blob/5ee7862793abc94c519e5b6d8e7d096563f092b4/examples/ansible.cfg#L357

**Comment by mboelen** [comment]
Initial work on this has been implemented. Use the latest version from GitHub (not the last release).

For now decided not to scan all home directories, as some machines could have hundreds/thousands of them. That could be a performance nightmare.

Thoughts?

**Comment by mboelen** [comment]
Closing

**Comment by dminca** [comment]
Thanks guys for including this feature! We're already benefiting from it, and never had any issues so far 👍

**Comment by mboelen** [comment]
You are welcome. Have a look at the other software stacks that you are using and want to have included, and create a new issue/request ;-)
