### ISSUE TITLE
bug: systemd=0 on systemd-powered Ubuntu 16.04

### ISSUE THREAD

**Issue by piotrkarbowski-ciklum** [CISOfy/lynis#440]
Hello.

Please be informed that the report yield `systemd=0` on a Ubuntu 16.04 system that does run systemd.

The `${ROOTDIR}usr/lib/systemd/systemd` does not exist on Ubuntu 16.04 installation.

btw, the `LogText` have typo, the first `systemd` should be renamed into `system`.

**Comment by mboelen** [comment]
Detection has been extended with commit https://github.com/CISOfy/lynis/commit/00648a636c35aa93099c95b29e72a92fd2c3dea2 and additional commit for changing the text.

Tested on Ubuntu 16.04 and looks good on system. Closing this issue, but feel free to reopen if your experience otherwise.

Thanks for the feedback!
