### ISSUE TITLE
MOTD not detected on Ubuntu with update-motd

### ISSUE THREAD

**Issue by tas50** [CISOfy/lynis#45]
Ubuntu systems can use update-motd to generate a motd file from .d files.  If you have this setup Lynis doesn't see your MOTD file.

**Comment by mboelen** [comment]
Thanks for the input. Can you show an example how you implemented it?

**Comment by quantumpacket** [comment]
Isn't `motd` meant for displaying a message after login and `issue`/`issue.net` meant for displaying a message at login prompt? If that is the case, what is the security benefit of using `motd` since a user needs to be authenticated to see it, opposed to the latter which can provide a disclaimer/warning text to a user prior to being authenticated? I use motd, but I see no security benefit to it unless it's meant to display system security information to certain users for administrative use. If that is the use case then how would it be determined if it's a pass/fail?

**Comment by tas50** [comment]
I think @quantumpacket has the better point here.  Issue and Issue.net are what you really care about.

**Comment by mboelen** [comment]
The related tests have been disabled, as focus on issue and issue.net is indeed better. Closing item with latest changes.
