### ISSUE TITLE
Minimal FreeBSD 11.1 reports hardening of 59%

### ISSUE THREAD

**Issue by ffries** [CISOfy/lynis#451]
Dear all,

First, congrats for Lynis, which I have been using under GNU/Linux for years. This is a nice tool for automated testing.

Now that I switched to FreeBSD, running Lynis on a fresh-minimal FreeBSD 11.1 installation with no daemon (not even SSH nor X) running and pf firewall returns ... hardening of 59%. This quite a low result, especially when comparing GNU/Linux security to FreeBSD security ...

The only known vulnerability in my system is /usr/bin/as being world executable.

I am still guessing where this 59% figure comes from, I am surprised.

It seems that GNU/Linux checks are performed against my BSD:
fs.protectedhardlinks ... are GNU/Linux kernel only.

Points are assigned when applications are installed (ex: virus scanner), when you should also take into account minimal systems with minimal vulnerabilities. Also, I don't understand why Lynis should reward users for installing plenty of applications, as applications bring vulnerabilities.

Kind regards,
French Fries

**Comment by mboelen** [comment]
Hi Fries :)

Points are assigned when things are tested. Obviously, a minimal installation is better than one polluted with all kind of tools.

The hardening index is just a number to give an idea on the hardening efforts. It is calculated on the actual tests that were performed. So that 59% may sound bad, but as you pointed out, you have a minimal install where not much controls were tested.

One thing that would help to get the 'base' score up on FreeBSD, is by creating more tests that test for basic functionality. So if you have suggestions on things we can additionally test on FreeBSD, that might be helpful.

**Comment by mboelen** [comment]
Hi @ffries - any suggestions you have to add as base tests for FreeBSD, to get the initial value higher for minimal FreeBSD installations?

**Comment by mboelen** [comment]
No response, closing issue for now.
