### ISSUE TITLE
Add command to show on screen the saved results of a previous test in the same pretty way as if tests were done right now 

### ISSUE THREAD

**Issue by q2dg** [CISOfy/lynis#516]
Neither lynis.log nor lynis-report.dat can't be used to show on screen their results in a pretty way (with colors, indentations, etc) like they are where tests are running in real time.
Thanks

**Comment by mboelen** [comment]
Lynis has different output streams: 1) Screen, 2) technical detailed log (lynis.log) 3) data report (lynis-report.dat). Each have their own purpose. If you like to see the related tests and more details on screen, have a look at --debug and --verbose.

We can't make the log/report pretty looking, besides what we already show on screen. Otherwise, have a look at the Enterprise functionality, that has different ways of presenting the information.

**Comment by q2dg** [comment]
Well, thanks. I've solved the situacion doing _lynis audit system | less -R_
