### ISSUE TITLE
Detection of files with SUID bit set

### ISSUE THREAD

**Issue by nodiscc** [CISOfy/lynis#558]
Hello,

It would be great if lynis allowed finding and listing files with `suid` permissions in the fashion of `find / -xdev -perm -4000 -o -perm -2000 -type f ! -path '/proc/*' -print`. Users could then whitelist certain files where the SUID permission is expected/unavoidable/known to be safe.

**Comment by mboelen** [comment]
Thanks for taking the time to add this suggestion.

Lynis does not run "expensive" scans on the file system due to the time it takes, and the differences in implementation of the find command on the different platforms (Linux, BSD, macOS, and others). It is very hard to make this a safe request that does not take a long time to run.

Also, we try to avoid tests that always will show some results and that the user has to do whitelist. Users typically will skip these or might not know what to do with it. So that means they need to be guided to make the choice between a safe or unsafe file.

If you still like this test to be added: add it as a custom test to tests_custom file in your include directory (lynis show includedir). That way you can implement it in the way it works for you.

Will close this issue for now.
