### ISSUE TITLE
NETW-2705: OpenShift Servers only have one entry in /etc/resolv.conf

### ISSUE THREAD

**Issue by Alex-L-ander** [CISOfy/lynis#583]
**Describe the bug**
On OpenShift Servers there is usually only one DNS Server entry in /etc/resolv.conf which points to the local machine. The entries which are really used are found in /etc/dnsmasq.d/origin-upstream-dns.conf.

**Version**
 - Distribution: RHEL 7.5
 - Lynis version 2.6.8

**Expected behavior**
If there is only one nameserver in /etc/resolv.conf, check for additional servers in /etc/dnsmasq.d/origin-upstream-dns.conf.

**Output**
-

**Additional context**
-

**Comment by mboelen** [comment]
Thanks for reporting!

Typically the system will still only use the entry in /etc/resolv.conf, even if that points to a local resolver. What do you have currently in your resolv.conf file?

**Comment by Alex-L-ander** [comment]
This is the content of the resolv.conf file:

`# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
# Generated by NetworkManager
search cluster.local
nameserver 10.0.0.1 # IP of Local System`

The file was edited upon the installation of the openshift playbook. I guess dns queries are forwarded to the servers named in /etc/dnsmasq.d/origin-upstream-dns.conf.

**Comment by mboelen** [comment]
Thanks. It is a little bit surprising that the Openshift playbook uses the local IP address instead of the localhost entry. Might be related to the clustering configuration.

Still, the Lynis test does its work. As it does not detect any localhost entry, it will assume that you are using an "external" resolver.

In this case, I would accept the finding and skip the test on this system. You know that 10.0.0.1 will take care of the resolving and has backups. You can use 'skip-test=' in your custom.prf file to disable this test.

(marked issue as wontfix, as making changes to the test is most likely not worth the time efforts and complexity at this time)
