### ISSUE TITLE
KRNL-5830: No vmlinuz or kernel images in /boot

### ISSUE THREAD

**Issue by werdck** [CISOfy/lynis#806]
**Describe the bug**
The program should check via a utility like linux's "file" command. I have several vmlinuz images, they are just called vm[kern-version].

**Version**
 - Distribution: Slackware current
 - Lynis version: master

**Expected behavior**
The vmlinuz images should be found even under a different name.

**Files that should be matched (but aren't)**
`/boot/vm5.3.7:          Linux kernel x86 boot executable bzImage, version 5.3.7 (root@<hostname>) #1 SMP Wed Oct 23 09:32:01 CEST 2019, RO-rootFS, swap_dev 0x4, Normal VGA`

**Comment by SchwarzerA** [comment]
KRNL-5830:4 is broken on openSUSE because they call their kernels differently:

-rw-r--r-- 1 root root   7352432 20. Sep 09:13 vmlinuz-4.12.14-lp151.28.16-default
-rw-r--r-- 1 root root   7311472  9. Okt 11:11 vmlinuz-4.12.14-lp151.28.20-default
…
-rw-r--r-- 1 root root  8909024 17. Okt 14:16 vmlinuz-5.3.6-1-default
-rw-r--r-- 1 root root  8909024 25. Okt 03:11 vmlinuz-5.3.7-1-default

**Comment by mboelen** [comment]
Thanks for reporting. Changes have been made to support more file names, including the one reported by @SchwarzerA 

Please test it and let me know if it does not work as expected.
