### ISSUE TITLE
FILE-6374 more specifically nosuid and noexec on tmp

### ISSUE THREAD

**Issue by JOduMonT** [CISOfy/lynis#823]
I wondering how many people are running /tmp with nosuid and noexec ?
It might be only on ubuntu and debian but those 2 options cause a lot of issue.

## the give simple example and easy to reproduce

- define noexec and try to launch a docker container
- define noexec and do an apt update or install
- define nosuid with etckeeper installed and tamper a file in /etc than update etckeeper database

**Comment by TheFlipside** [comment]
I use these mount options on all my systems and didn't run in major issues yet.
I haven't used a recent ubuntu/debian system in a while but I never had big problems with apt, only sometimes I see messages about perl packages not being able to be configured because of that but no backlash afterwards.
To be honest I don't run docker or etckeeper.

The only real issues I ran into was the proprietary nvidia driver installer but it allows to define a different directory than /tmp like /home/user/.tmp or whatever as workaround.
The other one is the VMware workstation installer and in that case I found the only workaround is to remount /tmp with exec and after the installer is done, remount again with noexec, not pretty but nothing can be perfect.

In my opinion these options should always be considered as the "should be" way to go for a system that aims for maximum security. When some software is unable to run without errors this way I see the need of changes on the side of the software vendors.

**Comment by mboelen** [comment]
Hi @JOduMonT - Thanks for your feedback and patience. We are working hard on the upcoming 3.0.0 major release, so it took a bit longer to respond.

Lynis makes suggestions to harden the system. That does not mean you have to apply every suggestion, especially not if it breaks expected functionality in your use-case. Every system and environment is different.

What you can do is exclude this particular test in your scan profile (`skip-test=FILE-6374`).
