### ISSUE TITLE
Allow SAK in KRNL-6000 test

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#87]
Currently Lynis complains if the ```kernel.sysrq``` sysctl value is not [0](https://github.com/CISOfy/lynis/blob/master/default.prf#L120). Most of the stuff provided by [magic sysrq](https://www.kernel.org/doc/Documentation/sysrq.txt) functionality can indeed decrease security, but there is at least one feature that increases security and that is the [secure attention key](https://en.wikipedia.org/wiki/Secure_attention_key) (SAK) feature.

I think Lynis should allow if SAK is enabled through ```kernel.sysrq```.

**Comment by kboratynski** [comment]
What is the added value of having `sysrq` feature like SAK in case it enables possibility to kill all processes (except `1`)? ;-)

Look at `Caution`[[1]] section. It is *not* recommended to use this feature for security reasons.
For desktops, feel free. ;-)

References:
[1.] https://www.debian.org/doc/manuals/debian-reference/ch09
[1]: https://www.debian.org/doc/manuals/debian-reference/ch09

**Comment by pyllyukko** [comment]
I was referring to only the ```k``` functionality, which you can use to kill [fake login screens](https://en.wikipedia.org/wiki/Login_spoofing).

**Comment by mboelen** [comment]
The KRNL-6000 test is a "container" test for boolean values. While the SAK feature is definitely interesting, I think the use-case for this is barely used. If one knows about this function, they can change the related sysctl value in their (custom) profile. So the default looks good as it is.

Thanks for reporting this insight!

Closing reason: default value will do for most users. For those using it, they can change their profile (instead of test).
