### ISSUE TITLE
No new release in 4 months

### ISSUE THREAD

**Issue by duck-rh** [CISOfy/lynis#892]
**Describe the bug**
Lynis LYNIS test suggest to upgrade because the installed software is more than 4 months old but there are no new releases.

**Version**
 - Distribution Debian
 - Lynis version 2.7.5

**Expected behavior**
The behavior is right but the test is based on a release frequency expectation that is probably not realistic.

**Comment by mboelen** [comment]
Yes it is a known issue and will be resolved with upcoming release. As this is a major release, it took longer than the normal release (usually one new version every month). So closing this issue, as we are getting really close to 3.0.0 ;-)

**Comment by duck-rh** [comment]
@mboelen you closed this ticket before solving it. The fact it is well known does not help at all. More than two months have passed and I see little activity on the git repo, so I guess that was premature.

So I would like this ticket to be reopened, not to put pressure on the release but to discuss how we can make this check better.

**Comment by mboelen** [comment]
@duck-rh The fix has already been applied, so that is why it is closed. We are preparing the new release in the background and the reason that changes are frozen until the release is available.

So the release is coming and the check is already improved.

**Comment by sazzle2611** [comment]
Same issue again, infact has been issue for long time but have been ignoring, the problem is we want to use Lynis to watch for possible security issues but instead I just end up deleting 100s of emails without even looking at them cause all most of them say is that the release is more than 4 months old. This means that I will miss any that are actually important.

We are on version 3.0.8
