### ISSUE TITLE
have FILE-7524 check for very basic misconfigurations

### ISSUE THREAD

**Issue by JoelStienlet** [CISOfy/lynis#937]
Hello all,

**Is your feature request related to a problem? Please describe.**
`sudo chmod 777 /`
`lynis audit system --tests FILE-7524`
`cat /tmp/lynis.log`
Result: "2020-05-31 11:59:44 File permissions are OK"
When they are obviously not...

**Describe the solution you'd like**
Add the most basic checks, like ownership and permissions of the main system paths.

**Additional context**
[Calamares doesn't check the rights on / either ](https://github.com/calamares/calamares/issues/1418) so some systems could be installed with a """really minor""" security hole...
I thought, why not do systematic testing by running lynis on every fresh install, to catch things like these? I tried the commands from the description, and it turns out the test was not really successful.

**Comment by mboelen** [comment]
Thanks for sharing.

The file permissions check uses only those paths that are defined in the default profile. The root directory itself is not tested at this moment. The reason is that it has different permissions (by default) on different platforms, so defining a good value (without specifying a platform as well) is not that simple.

Have a look at the default profile. Feel free to add additional paths to custom.prf if you like to have them tested. Will close this issue for now, as part of the upcoming major release.
