### ISSUE TITLE
ZFS test incorrectly assumes FreeBSD only?

### ISSUE THREAD

**Issue by PaulGWebster** [CISOfy/lynis#940]
**Describe the bug**
From the log:
2020-06-02 15:06:06 ====
2020-06-02 15:06:06 Skipped test FILE-6330 (Checking ZFS file systems)
2020-06-02 15:06:06 Reason to skip: Incorrect guest OS (FreeBSD only)

**Version**
 - Latest gentoo
 - Latest lyris

**Expected behavior*
A check as I am running zfs quite extensively

<pre>
 # zfs list | wc -l
5221
..
zstore/sys                                                                            10.8G   340G       96K  /mnt/zstore/sys
zstore/sys/usr                                                                        10.8G   340G       96K  /mnt/zstore/sys/usr
zstore/sys/usr/portage                                                                9.31G   340G       96K  /mnt/zstore/sys/usr/portage
zstore/sys/usr/portage/distfiles                                                      9.31G   340G     9.31G  /usr/portage/distfiles
zstore/sys/usr/src                                                                    1.51G   340G     1.51G  /usr/src

</pre>

**Output**
Unknown just mentioning it thinks I am not running zfs which most of my filesystem is based on :P

**Additional context**

**Comment by mboelen** [comment]
The reason the test is skipping because it uses a (Free)BSD-specific mount point option `-p`.

Now this test could be made more generic. For example, the test could do this based on OS or if the zfs command is available, use that to query (root permissions needed?).

Are you willing to submit some pull requests to improve this test together?
